"""
StarMeet Astro Brain - 12-Stage Astrological Calculator

This module analyzes Vedic horoscopes using a digital_twin JSON
(generated by jyotishganit library) and produces structured output
for LLM interpretation.

Architecture:
    digital_twin (JSON) -> Calculator (12 stages) -> CalculatorOutput -> LLM -> Report

Stages:
    1. Core Personality (D1)
    2. Soul Blueprint (D9)
    3. Yogas & Combinations
    4. Wealth Potential (D2, D11)
    5. Skills & Intelligence (D24)
    6. Career & Ambition (D10)
    7. Creativity & Expression (D5)
    8. Gains & Networking (D11)
    9. Karmic Patterns (D60)
    10. Timing Analysis (Dasha)
    11. Nakshatra Deep Dive
    12. Jaimini System
"""

from .calculator import AstroBrain

__version__ = "1.0.0"
__all__ = ["AstroBrain"]
